version: "3.0"

# Services to run
services:
  mongo_db: # name of BD service
    image: mongo
    container_name: mongo_entrega12
    ports:
      - 27017:27017
    volumes:
      - entrega12:/data/configdb
      - entrega12:/data/db
    restart: always

networks:
  nodejs-network:
    name: nodejs-network
    driver: bridge

volumes:
  entrega12: